Update Untagged.yaml

diff --git a/.github/workflows/Untagged.yaml b/.github/workflows/Untagged.yaml
--- a/.github/workflows/Untagged.yaml
+++ b/.github/workflows/Untagged.yaml
@@ -154,7 +154,7 @@ jobs:
 
     - name: Purge tag - latest-${{needs.Build.outputs.DSOALBranch}}
       run: |
-        gh release delete latest-${{needs.Build.outputs.DSOALBranch}} --repo ${{env.DSOALRepo}} --cleanup-tag --yes || true
+        #gh release delete latest-${{needs.Build.outputs.DSOALBranch}} --repo ${{env.DSOALRepo}} --cleanup-tag --yes || true
 
     - name: Release - archive
       run: |
